---
baseURL: /
languageCode: en-us
title: thoughtexpo
enableRobotsTXT: true
enableGitInfo: true
summaryLength: 25
build:
  writeStats: true

taxanomies:
  tag: tags

permalinks:
  blog: /:filename/

params:
  description: "@leela_vg corner in the internet"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
...