baseURL: https://thoughtexpo.com/
languageCode: en-us
defaultContentLanguage: en
title: thoughtexpo
enableRobotsTXT: true

taxanomies:
  tag: "tags"

permalinks:
  blog: "/:filename/"

params:
  homeText: "Placeholder until the actual blog is up"
  dateFormat: "Jan 2, 2006"

menu:
  main:
    - name: "Home"
      pre: "home"
      url: "/"
      weight: 1
    - name: "Blog"
      pre: "edit"
      url: "/blog/"
      weight: 2
    - name: "Tags"
      pre: "tag"
      url: "/tags/"
      weight: 3
