---
baseURL: /
languageCode: en-us
title: thoughtexpo
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
pygmentsCodeFences: true
pygmentsUseClasses: true
canonifyURLs: true
summaryLength: 25

build:
  writeStats: true

taxanomies:
  tag: tags

permalinks:
  blog: /:filename/

params:
  author: Leela Venkaiah G
  twitter: leela_vg
  github: leelavg
  linkedin: leelavg
  description: '@leela_vg corner in the internet'
  search: true
  goat_counter: leelavg
  contact: >
    [Twitter](https://twitter.com/leela_vg) /
    [GitHub](https://github.com/leelavg) /
    [LinkedIn](https://www.linkedin.com/in/leelavg)
  footer: >
    Made with [Hugo](https://gohugo.io/) &bull;
    Deployed on [Netlify](https://www.netlify.com/) &bull;
    Content in [GitHub](https://github.com/leelavg/thoughtexpo)

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
...
