[build.environment]
HUGO_VERSION = "0.69.0"

[context.production]
environment = {HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true", NODE_ENV = "production"}
command = "hugo -b 'thoughtexpo.com' --gc --minify --cleanDestinationDir"

[context.branch-deploy]
environment = {HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true", NODE_ENV = "production"}
command = "hugo -b 'stage.thoughtexpo.com' --gc --minify --cleanDestinationDir"
