[build.environment]
HUGO_VERSION = "0.74.0"

[context.production]
environment = { HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true", NODE_ENV = "production" }
command = "hugo -b 'https://thoughtexpo.com' --gc --minify --cleanDestinationDir"

[context.branch-deploy]
environment = { HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true", NODE_ENV = "production" }
command = "hugo -b 'https://stage.thoughtexpo.com' --gc --minify --cleanDestinationDir"
